"""migration

Revision ID: 59abdf812c85
Revises: 9e1578708bb2
Create Date: 2024-07-17 12:03:58.595247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59abdf812c85'
down_revision = '9e1578708bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('completion_date')

    # ### end Alembic commands ###
